
services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - nextcloud_net

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   command: ["redis-server", "--appendonly", "yes"]
  #   env_file:
  #     - ./.env
  #   ports:
  #     - ${REDIS_HOST_PORT}:6379
  #   volumes:
  #     - redis_data:/data

  app:
    image: nextcloud
    depends_on:
      # - redis
      - db
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - ./.env
    networks:
      - nextcloud_net

volumes:
  nextcloud:
  db:
  redis_data:

networks:
  nextcloud_net: