services:
  minio_cloud:
    build: minio
    container_name: minio_cloud
    ports:
      - ${MINIO_PORT}:9000
      - 9001:9001
    volumes:
      - minio_cloud_volume:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}
    restart: always

volumes:
  minio_cloud_volume:
