services:
  wordpress:
    container_name: wordpress
    build: .
    restart: always
    env_file: ./.env
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    networks:
      - wordpress_network
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
      - mysql_data:/var/lib/mysql

networks:
  wordpress_network:
    driver: bridge

volumes:
  wordpress:
  mysql_data:
