services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: openssh-server
    hostname: openssh-server #optional
    env_file:
      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY=${PUBLIC_KEY} #optional
      - PUBLIC_KEY_FILE=${PUBLIC_KEY_FILE} #optional
      - PUBLIC_KEY_DIR=${PUBLIC_KEY_DIR} #optional
      - PUBLIC_KEY_URL=${PUBLIC_KEY_URL} #optional
      - SUDO_ACCESS=${SUDO_ACCESS}
      - PASSWORD_ACCESS=${PASSWORD_ACCESS} #optional
      - USER_PASSWORD=${USER_PASSWORD} #optional
      - USER_PASSWORD_FILE=${USER_PASSWORD_FILE} #optional
      - USER_NAME=${USER_NAME} #optional
      - LOG_STDOUT=${LOG_STDOUT} #optional
    volumes:
      - /path/to/openssh-server/config:/config
    ports:
      - 2222:2222
    restart: unless-stopped