services:
  backend:
    # depends_on:
    #   - ...
    container_name: nest_backend
    build: ./backend
    image: node:latest
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    # networks:
    #   - ...
    restart: always
