# Base image
FROM python:latest

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
RUN pip install django
COPY . .

RUN python manage.py makemigrations && python manage.py migrate --run-syncdb

# Start the server using the production build
CMD [ "python", "manage.py", "runserver" ]
