services:
  adminer:
    env_file:
      - ./.env
    container_name: wordpress
    image: wordpress:latest
    ports:
      - ${WORDPRESS_PORT}:8080
    # networks:
    #   - ...
    restart: always
