services:
  mysql:
    env_file:
      - ./.env
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_VOLUME_NAME}:/home/data
    restart: always

volumes:
  ${MYSQL_VOLUME_NAME}:
